"""create user roles

Revision ID: fc82389b3760
Revises: ce3f8f1d0d9e
Create Date: 2025-01-21 19:22:41.288189

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

from app.users.constants import USER_ROLE


# revision identifiers, used by Alembic.
revision: str = "fc82389b3760"
down_revision: Union[str, None] = "ce3f8f1d0d9e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sqlalchemy_utils.types.choice.ChoiceType(USER_ROLE),
            nullable=True,
            default="regular_user",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
